### ISSUE TITLE
pull request problem

### ISSUE THREAD

**Issue by Helo-Man** [everpcpc/pixiv#2]
I use the same workflows, it pass in my repository,but when I creat a pull request ,it show missing 'REFRESH_TOKEN' error.

**Comment by Helo-Man** [comment]
I know , there should have a coverage.txt file. What content should coverage.txt have? Can you give me a demo?
测试用的文件应该有什么内容能看看嘛？

**Comment by Helo-Man** [comment]
https://github.com/Helo-Man/pixiv/runs/563331695?check_suite_focus=true
https://github.com/everpcpc/pixiv/runs/563331790?check_suite_focus=true

**Comment by everpcpc** [comment]
fixed by https://github.com/everpcpc/pixiv/commit/0ad96f34937bf694e40161044a7164009753dd81
