### ISSUE TITLE
Error 403

### ISSUE THREAD

**Issue by VTGare** [everpcpc/pixiv#5]
Yesterday Login function started returning an error 403

Login credits are correct. Tried a new account, it still didn't work.

**Comment by everpcpc** [comment]
seems like https://github.com/upbit/pixivpy/issues/140

**Comment by SpiffyEight77** [comment]
> seems like [upbit/pixivpy#140](https://github.com/upbit/pixivpy/issues/140)

I can't reproduce the error 403 in my local env, but I got following issue
```
invalid character '<' looking for beginning of value
```
And after change the version from ```"PixivAndroidApp/5.0.64 (Android 6.0)"```to```"PixivAndroidApp/5.0.115 (Android 6.0)"``` and the problem fixed.

**Comment by roytam1** [comment]
... and now you'll get HTTP 400 instead. https://github.com/upbit/pixivpy/issues/158

**Comment by everpcpc** [comment]
a workaround to get refresh code manually:
https://gist.github.com/upbit/6edda27cb1644e94183291109b8a5fde
